version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/todo_list
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment: #MySQL 로그인 정보 추가
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: abcd1234
      MYSQL_DB: todolist_db

  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist_db
      MYSQL_USER: user
      MYSQL_PASSWORD: abcd1234
    ports:
      - "3307:3306"
    restart: always

volumes:
  db-data: