# Generated by Django 5.0.4 on 2024-04-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('완료', '완료'), ('진행중', '진행중'), ('미완료', '미완료')], default='미완료', max_length=10),
        ),
    ]
