# Generated by Django 5.0.4 on 2024-04-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('today', 'Today'), ('study', 'Study'), ('work', 'Work')], default='today', max_length=10)),
                ('content', models.TextField()),
                ('due_date', models.DateField()),
                ('priority', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
            ],
        ),
    ]
